- package-lock.json
- package.json
- src/renderer/App.tsx
- src/renderer/ConnectDialog.tsx
- src/renderer/Jobs.tsx
- src/renderer/Models.tsx
- src/renderer/NavBar.tsx
- src/renderer/Registration.tsx
- src/renderer/components/ui/navigation-menu.tsx
- src/renderer/components/ui/table.tsx
> finished nav bar & register page

- src/renderer/App.tsx
- src/renderer/ModelDetails.tsx
- src/renderer/ModelRun.tsx
- src/renderer/Models.tsx
- src/renderer/NavBar.tsx
> finished available models page

- .erb/scripts/delete-source-maps.js
- package-lock.json
- package.json
- src/main/handlers/models.ts
- src/main/handlers/registration.ts
- src/main/main.ts
- src/main/models/ml-model.ts
- src/main/models/model-server.ts
- src/main/preload.ts
- src/renderer/preload.d.ts
Closes #20 
Closes #21 
Closes #22
> Add registration and models backend api

- src/renderer/App.tsx
- src/renderer/ConnectDialog.tsx
- src/renderer/JobViewDetails.tsx
- src/renderer/Jobs.tsx
- src/renderer/Models.tsx
- src/renderer/Registration.tsx
- src/renderer/Types.ts
- src/renderer/index.ejs
- src/renderer/sample_models.json
> Styling Registration Page

- src/renderer/Models.tsx
> Style the models page

- src/renderer/App.tsx
- src/renderer/NavBar.tsx
- src/renderer/Registration.tsx
> Nav Bar Styling

- src/renderer/App.tsx
> Add footer and remove scrolling

- package-lock.json
- package.json
- src/main/database/database-conn.ts
- src/main/handlers/job.ts
- src/main/handlers/registration.ts
- src/main/main.ts
- src/main/models/job.ts
- src/main/preload.ts
Note: This PR doesn't include the files API or invocation of jobs (by calling a FlaskML endpoint). Has to do with #24.
> Add job handlers and API

- src/renderer/App.tsx
- src/renderer/ConnectDialog.tsx
- src/renderer/JobViewDetails.tsx
- src/renderer/JobViewLayout.tsx
- src/renderer/Jobs.tsx
- src/renderer/ModelDetails.tsx
- src/renderer/Models.tsx
- src/renderer/NavBar.tsx
- src/renderer/Registration.tsx
Closes #10 
Finished this page's structure for  a sample model
> Specific models page

- src/main/main.ts
- src/renderer/App.css
- src/renderer/App.tsx
> Add a custom title bar

- src/renderer/ConnectDialog.tsx
- src/renderer/Registration.tsx
> Add default value for connect dialog

- src/main/main.ts
> Fix title bar for Windows

- src/renderer/ConnectDialog.tsx
- src/renderer/Jobs.tsx
- src/renderer/Models.tsx
- src/renderer/Registration.tsx
- src/renderer/Types.ts
- src/renderer/components/ConnectIcon.tsx
- src/renderer/components/GreenRunIcon.tsx
> refactored and fixed buttons for jobs page

- src/main/database/database-conn.ts
- src/main/database/dummy_data/jobs.json
- src/main/database/dummy_data/mlmodels.json
- src/main/database/dummy_data/servers.json
- src/main/database/sqlite-db.ts
- src/main/main.ts
> Initialize DB with Dummy Data at Startup

- package-lock.json
- package.json
- src/main/handlers/job.ts
- src/main/models/job.ts
- src/renderer/JobViewDetails.tsx
- src/renderer/JobViewLayout.tsx
- src/renderer/JobViewOutputs.tsx
- src/renderer/Jobs.tsx
- src/renderer/lib/hooks.ts
- src/shared/models.ts
> [Integration] Integrate Backend for Jobs

- src/renderer/Models.tsx
- src/renderer/components/LoadingScreen.tsx
> Add loading screen for models page

- src/renderer/JobViewDetails.tsx
- src/renderer/Jobs.tsx
Probably need to show some confirmation dialog before deleting. Let me know if that should be a part of this PR or not.
> Handle deletion of jobs

- .github/workflows/publish.yml
> Add windows/linux support to publish release

- src/main/handlers/registration.ts
- src/main/models/job.ts
- src/main/models/model-server.ts
- src/main/util.ts
- src/shared/models.ts
> Refactor shared models to remove duplication

- src/renderer/Jobs.tsx
Previous PR was incomplete and didn't actually remove the warning. Closes #130.
> Actually fix validateDOMNesting warning

- src/renderer/Jobs.tsx
- src/renderer/RegistrationTable.tsx
> Make all tables start from the same height

- src/renderer/ModelDetails.tsx
> Styling for model inspect page

- src/renderer/Jobs.tsx
- src/renderer/components/CancelIcon.tsx
- src/renderer/components/DeleteIcon.tsx
Closes #132 
Can be merged after #150
> Styling for consistent jobs view

- package.json
- src/renderer/lib/hooks.ts
Closes #26 
Can be merged after #149
> Implements Polling for Jobs View

- src/renderer/ConnectDialog.tsx
Closes #134.
`Connect` button is disabled until user input follows this format: `[0-255].[0-255].[0-255].[0-255]:[0-99999]` (or `localhost` for IP).
> Add form validation for server registration

- src/renderer/JobViewDetails.tsx
- src/renderer/Jobs.tsx
> Format dates in Jobs table and Job Details page

- src/renderer/JobViewDetails.tsx
- src/renderer/components/FilePathField.tsx
- src/renderer/components/ui/textarea.tsx
> Improve Job details page UI

- src/main/database/sqlite-db.ts
> Fix "Unable to Connect to SQLite Database" bug

- src/main/database/dummy_data/mlmodels.ts
- src/main/handlers/job.ts
- src/main/handlers/models.ts
- src/main/handlers/registration.ts
- src/main/main.ts
- src/main/model-apps/config.ts
- src/main/model-apps/isr-model/isr-model-config.ts
- src/main/model-apps/isr-model/isr-model-service.ts
- src/main/model-apps/ten-second-model/ten-second-model-config.ts
- src/main/preload.ts
- src/renderer/ModelDetails.tsx
- src/renderer/lib/hooks.ts
- src/shared/models.ts
For now I have still just displayed the information from the respective ModelAppConfig in the ModelDetails page. Creating a separate issue to refactor that component.
Closes #128
> Refactor Model App structure and extend ModelAppConfig

- src/renderer/Models.tsx
- src/renderer/ModelsTable.tsx
Closes #162.
Available and Unavailable Models:
No Available Models:
> Show unavailable models in a separate table

- src/main/database/dummy_data/servers.ts
- src/main/database/sqlite-db.ts
- src/main/handlers/file-system.ts
- src/main/handlers/registration.ts
- src/main/models/model-server.ts
- src/renderer/RegistrationTable.tsx
- src/renderer/utils.ts
> Add default registration values to Registration Page when available

- package-lock.json
- package.json
- src/main/database/database-conn.ts
- src/main/database/migrations/0000_models.ts
- src/main/database/migrations/0001_jobs.ts
- src/main/database/migrations/0002_servers.ts
- src/main/database/migrations/0003_servers_add_col.ts
- src/main/database/migrations/umzug.ts
- src/main/database/sqlite-db.ts
Closes #182 
Changes are not backward compatible. Ensure you delete your database file before proceeding.
> Add migrations support

- src/renderer/App.tsx
- src/renderer/model-apps/sbf-model/SBFModelRun.tsx
> Add back button

- src/main/database/dummy_data/jobs.ts
- src/main/database/migrations/0006_jobs_add_request.ts
- src/main/database/migrations/umzug.ts
- src/main/flask-ml/task-service.ts
- src/main/handlers/file-system.ts
- src/main/handlers/job.ts
- src/main/main.ts
- src/main/models/job.ts
- src/main/preload.ts
- src/shared/generated_models.ts
- src/shared/openapi.yaml
- Replaced `inputs` and `parameters` attributes of `Job` with `request: RequestBody`. Added corresponding migration. 
- Added some selection utilities for selecting files and directories that we'll need later. 
- Added BatchDirectoryInput and BatchDirectoryResponse to `generated_models.ts`. They weren't included before for some reason.
> Add request attribute to job in addition to selection utilities

- src/main/flask-ml/task-service.ts
- src/main/handlers/job.ts
- src/renderer/components/input_fields/BatchFileField.tsx
- src/renderer/components/input_fields/BatchTextField.tsx
- src/renderer/components/parameter_fields/EnumField.tsx
- src/renderer/components/parameter_fields/FloatField.tsx
- src/renderer/components/parameter_fields/IntField.tsx
- src/renderer/components/parameter_fields/RangedFloatField.tsx
- src/renderer/components/parameter_fields/RangedIntField.tsx
- src/renderer/components/parameter_fields/TextField.tsx
- src/renderer/lib/utils.ts
- src/renderer/models/ModelRunTask.tsx
- src/shared/dummy_data/task_schema4.ts
> Validation for Run Page Form Fields + Convert FormData to RequestBody

- src/main/flask-ml/task-service.ts
- src/renderer/App.css
- src/renderer/lib/hooks.ts
- src/renderer/models/ModelRun.tsx
- src/renderer/models/ModelRunTask.tsx
Closes #232 
Closes #231 
The cause of the bug was the scrollbar (it only appears if the form is long enough, so the elements shift to the left to make room). Let me know what you guys think. Another option is hiding the scrollbar completely, although I don't know if that's user-friendly. Looks like this on pages without overflow.
> Fix layout shift with permanent scrollbar

- src/main/flask-ml/model-app-service.ts
- src/main/handlers/job.ts
- src/main/handlers/registration.ts
- src/main/handlers/task.ts
- src/renderer/models/ModelRunTask.tsx
- src/shared/dummy_data/api_routes.ts
- src/shared/models.ts
> Refactor task service

- package-lock.json
- package.json
- src/main/database/database-conn.ts
- src/main/database/dummy_data/mlmodels.ts
- src/main/database/sqlite-db.ts
- src/main/flask-ml/model-app-service.ts
- src/main/flask-ml/register-model-service.ts
- src/main/handlers/registration.ts
- src/main/main.ts
- src/main/models/ml-model.ts
- src/main/models/model-server.ts
- src/main/preload.ts
- src/renderer/App.tsx
- src/renderer/components/RegisterModelButton.tsx
- src/renderer/components/ui/button.tsx
- src/renderer/lib/hooks.ts
- src/renderer/models/Models.tsx
- src/renderer/registration/ConnectDialog.tsx
- src/renderer/registration/Modal.tsx
- src/renderer/registration/ModelAppConnect.tsx
- src/renderer/registration/ModelConnectionButton.tsx
- src/renderer/registration/Registration.tsx
- src/renderer/registration/RegistrationTable.tsx
- src/shared/dummy_data/set_dummy_mode.ts
Closes #229 
https://github.com/user-attachments/assets/fb719203-bad0-4057-94f5-36378a663359
Run model page doesn't work because of snake case.
> Support new Registration Flow

- package-lock.json
- package.json
- src/main/flask-ml/model-app-service.ts
- src/main/flask-ml/register-model-service.ts
- src/main/main.ts
- src/renderer/jobs/JobViewDetails.tsx
- src/renderer/lib/utils.ts
> Add snake case and other fixes

- package-lock.json
- package.json
- src/__mocks__/RehypeExternalLinksMock.ts
- src/main/handlers/registration.ts
- src/renderer/models/ModelDetails.tsx
- src/renderer/models/ModelRunTask.tsx
- Add react-markdown plugin so that markdown links open in browser window #254
- Fixes animation on Model Run Task page
- Fixes registration logic that determines when a model is new, and when it has been seen before
> Add react-markdown plugin so that markdown links open in browser window and other changes

- src/main/flask-ml/model-app-service.ts
- src/main/flask-ml/register-model-service.ts
- src/renderer/models/Models.tsx
- src/renderer/registration/ModelAppConnect.tsx
- src/renderer/registration/RegistrationTable.tsx
Closes #240
https://github.com/user-attachments/assets/0b930fca-7d0a-42bc-ac36-f765f0953903
> Add error handling for model app registration

- package-lock.json
- package.json
- src/renderer/jobs/JobViewOutputs.tsx
- src/renderer/jobs/PreviewResponseBody.tsx
- src/shared/generated_models.ts
- src/shared/openapi.yaml
Closes #251
Added dispatch for response body.
> Prepare preview component

- src/main/database/dummy_data/jobs.ts
- src/renderer/jobs/JobViewDetails.tsx
Fixes bug on Jobs page when clicking on the ISR job's view button.
> Update ISR dummy data

- src/renderer/registration/ModelAppConnect.tsx
> Quick select

- src/renderer/jobs/Jobs.tsx
> reduced Jobs page to a single table for both running and finished jobs

- src/renderer/jobs/sub-components/StatusComponent.tsx
> finished removing retry

- src/renderer/components/PreviewFileResponse.tsx
- src/renderer/components/response_body/BatchFileResponseView.tsx
Preview button wasn't working after #270 went in. Fixed.
> Fix preview button

- src/renderer/models/ModelRunTask.tsx
https://github.com/user-attachments/assets/6cdafbe7-8178-47b4-9467-da58f1f8c75f
> Await run job before navigation

- src/renderer/components/response_body/text_views/TextView.tsx
- src/renderer/jobs/JobViewOutputs.tsx
- src/renderer/jobs/PreviewResponseBody.tsx
- src/shared/dummy_data/batchtext_response.ts
> Add TextView Component

- src/renderer/components/PreviewFileResponse.tsx
- src/renderer/components/response_body/file_views/FileView.tsx
- src/renderer/components/response_body/previews/CSVPreview.tsx
- src/renderer/components/response_body/previews/FilePreview.tsx
- src/renderer/components/response_body/previews/ImagePreview.tsx
- src/renderer/components/response_body/previews/JSONPreview.tsx
- src/renderer/components/response_body/previews/MarkdownPreview.tsx
- src/renderer/components/response_body/previews/TextPreview.tsx
- src/renderer/jobs/JobViewOutputs.tsx
- src/renderer/jobs/PreviewResponseBody.tsx
- src/shared/dummy_data/batchfile_response.ts
> Add FileView Component

- src/renderer/lib/utils.ts
- src/renderer/models/ModelRunTask.tsx
> Add unavailable task dialog

- src/main/handlers/job.ts
- src/main/main.ts
- src/main/preload.ts
- src/main/util.ts
- src/renderer/App.tsx
- src/renderer/navigation/NavigationListener.tsx
- src/renderer/preload.d.ts
Closes #218 
Works on Windows. Should check on MacOS and Linux to see if anything additional needs to be done.
> Add notifications for job completion/failure

- package-lock.json
- package.json
Fix based on 
https://github.com/electron-userland/electron-builder/issues/5850#issuecomment-1821648559
> Fix Apple Silicon Mac Build

- package.json
- src/renderer/components/response_body/file_views/BatchFileGrid.tsx
- src/shared/generated_models.ts
- src/shared/openapi.yaml
> Modify openapi.yaml and fix toLowerCase issue

- README.md
> Added Instructions for Linux to README

- src/main/services/model-app-service.ts
- src/main/services/register-model-service.ts
> Fix multiple models on same IP/port show connected at the same time

- src/renderer/components/PreviewFileResponse.tsx
- src/renderer/components/response_body/file_views/FileView.tsx
> Fix video title

- src/main/database/migrations/0011_models_add_is_removed.ts
- src/main/database/migrations/umzug.ts
- src/main/handlers/models.ts
- src/main/main.ts
- src/main/models/ml-model.ts
- src/main/preload.ts
- src/main/services/register-model-service.ts
- src/renderer/components/custom_ui/RegisterModelButton.tsx
- src/renderer/components/custom_ui/customButtons.tsx
- src/renderer/jobs/JobViewDetails.tsx
- src/renderer/jobs/Jobs.tsx
- src/renderer/models/Models.tsx
- src/renderer/models/ModelsTable.tsx
- src/renderer/registration/RegistrationTable.tsx
- src/shared/dummy_data/set_dummy_mode.ts
> Added version number, remove and  restoring previously connected features for models
